# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [28]:
# I import the numpy package
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [30]:
print("The numpy version is:", np.__version__)


The numpy version is: 2.3.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [ ]:

a = np.random.randint(10, size=(2,3,5))
#a = np.random.random(10, size=(2,3,5))
#a = np.random.rand(10,2,3,5)




### 4. Print a.


In [34]:
print("The 3 dimensional array is:\n ",a)

The 3 dimensional array is:
  [[[5 1 2 1 1]
  [6 4 5 5 0]
  [5 2 2 0 3]]

 [[7 4 6 0 1]
  [3 2 6 9 5]
  [8 8 5 8 8]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [35]:
b = np.ones((5,2,3))


### 6. Print b.


In [36]:
print("Array b: \n",b)


Array b: 
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [38]:
### [your code here]
# Original source: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-180.php 

def test_array_dimensions(ar1, ar2):
    try:
        # Attempting to add arrays ar1 and ar2
        ar1 + ar2
    except ValueError:
        # If ValueError occurs (arrays have different dimensions), return "Different dimensions"
        return "Different dimensions"
    else:
        # If no error occurs (arrays have the same dimensions), return "Same dimensions"
        return "Same dimensions"

test_array_dimensions(a,b)


# Or second method

#if a.size == b.size:
#    print("A and b have the same dimensions")

'Different dimensions'


### 8. Are you able to add a and b? Why or why not?


In [ ]:
"""
No, it's not possible due to the two numpy arrays don't 
have different shapes and dimensions, we should transpose and reshape them

"""

b = b.reshape((2,3,5))
print("Array c: \n", c)



Array c: 
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to variable "c".


In [ ]:
c = a+b



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
d = c +a
# They have same dimensions and shape
print("Array d = a + c:\n", d)

Array d = a + c:
 [[[11.  3.  5.  3.  3.]
  [13.  9. 11. 11.  1.]
  [11.  5.  5.  1.  7.]]

 [[15.  9. 13.  1.  3.]
  [ 7.  5. 13. 19. 11.]
  [17. 17. 11. 17. 17.]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [45]:
print("a.min:", a.min(), "d.min:", d.min())
print("a.max:", a.max(), "d.max:", d.max())
print("a.mean:", a.mean(), "d.mean:", d.mean())

a.min: 0 d.min: 1.0
a.max: 9 d.max: 19.0
a.mean: 4.066666666666666 d.mean: 9.133333333333333



### 12. Multiply a and c. Assign the result to e.


In [ ]:
e = a * c




### 13. Does e equal to a? Why or why not?


In [ ]:
e == a

array([[[ True, False,  True, False,  True],
        [False, False, False, False,  True],
        [False, False,  True, False, False]],

       [[False, False, False, False, False],
        [ True, False,  True, False, False],
        [ True,  True, False, False, False]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [ ]:

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("d_max:", d_max, "d_min:", d_min, "d_mean:", d_mean)

d_max: 19.0 d_min: 1.0 d_mean: 9.133333333333333



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [48]:
### [your code here]

# Original source: https://docs.vultr.com/python/third-party/numpy/empty
f = np.empty(f_shape)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [49]:

f = np.empty_like(d)

for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            value = d[ x, y, z]
            
            if value == d_min:
                f[x,y,z] = 0
            elif value == d_max:
                f[x,y,z] = 100
            elif value == d_mean:
                f[x,y,z] = 50
            elif d_min < value < d_mean:
                f[x,y,z] = 25
            elif d_mean < value < d_max:
                f[x,y,z] = 75
            
    





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:

print(f)

[[[ 75.  25.  25.  25.  25.]
  [ 75.  25.  75.  75.   0.]
  [ 75.  25.  25.   0.  25.]]

 [[ 75.  25.  75.   0.  25.]
  [ 25.  25.  75. 100.  75.]
  [ 75.  75.  75.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [51]:
g = np.empty(d.shape, dtype=str)

for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            value = d[x, y, z]
            if value == d_min:
                g[x, y, z] = "A"
            elif value == d_max:
                g[x, y, z] = "E"
            elif value == d_mean:
                g[x, y, z] = "C"
            elif d_min < value < d_mean:
                g[x, y, z] = "B"
            elif d_mean < value < d_max:
                g[x, y, z] = "D"
